### ISSUE TITLE
Fix the size of the footer image

### ISSUE THREAD

**Issue by tanius** [edgeryders/ngi-forward-platform#1]
Currently, there is an image `/assets/images/OC-EC-H2020.jpg` at the bottom of the https://ngi.edgeryders.eu/ pages.

When shown in 100% scale as done by default, on small screen resolutions like 1024×768 px it will appear with too large text and also introduce a horizontal scrollbar.

It should made to fit the page content width, including on smartphone screens.

**Comment by damingo** [comment]
Done
