### ISSUE TITLE
Fill section "Partners" with the partner organization logos

### ISSUE THREAD

**Issue by tanius** [edgeryders/ngi-forward-platform#13]
This refers to this section: https://ngi.edgeryders.eu/#partners

The process to solve this issue is as follows:

1. Obtain the logos and put them into [a private folder](https://drive.google.com/drive/folders/1CJC_XguLdPeqbZbhsHNSEfQpkh3JjiQZ) in a uniform size (here, 130 px high). This is done by now.

2. @maribati: please agree with each of the partner organizations on logo use, in writing. This includes:

    * Obtain written permission from each organization that we can use their logo. You can send them the logo as we intend to use it, and a link to the location where we intend to use it: https://ngi.edgeryders.eu/#partners
    * Ask them to provide a different logo file, ideally in a vector format, if we should use a different one.
    * Ask them for the link where the logo should point to. This can be nothing (no link), the frontpage of their website, or a sub-page they have set up about their involvement in the NGI Forward project.
    * Post relevant excerpts of their answers as a comment to this issue. So we have a public record that we use the logos properly.

3. @damingo: Once the above two steps are done, please add the logos at https://ngi.edgeryders.eu/#partners . The logos should be presented in a reasonable layout, such as rows with 3 or 4 logos each. Each logo should be linked to the link target given by the partner organization, namely:

    * for Resonance Design: https://www.theinternetofthings.eu/
    * for Nesta: no link
    * for Edgeryders OÜ: https://edgeryders.eu/t/6640
    * for Aarhus University: https://international.au.dk/
    * for City of Amsterdam: https://www.amsterdam.nl/
    * for University of Warsaw: http://en.uw.edu.pl/
    * for Nesta Italia: https://www.nestaitalia.org/

4. @tanius: Create a prominent notice in `README.md` and in a special readme in the logos' directory that the logos are not covered by the open source licence of this repository, but are copyrighted materials licenced for use on https://ngi.edgeryders.eu/ only.

**Comment by maribati** [comment]
Related to the task number 2: today (30/5) I received the response from Rob Van Kranenburg (Resonance Design):

> That is correct. Of course you have permission. You can link it to
> https://www.theinternetofthings.eu

**Comment by maribati** [comment]
Among the listed partners on the website "NESTA Italia" is missing. I sent them the e-mail and requested the logo.

**Comment by maribati** [comment]
today (30/5) response from Heshani Jayaratne, NESTA, UK:

> replying to your questions:
> 1) yes
> 2) yes
> 3) nothing for the time being - I guess we can add something later in case"

(my questions were: 

1. can you confirm that this is a correct version to use? If not, please send us your official logo in vector format.
2. can you give us the permission to use the logo? 
3. where the logo should point to?)

**Comment by tanius** [comment]
@damingo You can now start working on this issue. We have three logos for now, which I have added to the repo as [`assets/images`](https://github.com/edgeryders/ngi-forward-platform/tree/master/assets/images)`/logo-*.png` in a standardized format (white background, 130 px high).

For the four organizations where permission to use the logo is still outstanding, for now please use a 130 px high picture with white background and the name of the organization written inside, or create the equivalent in HTML.

For the full list of organizations and the link targets, see the top of this issue.

**Comment by maribati** [comment]
today (3/6), response from Mirko Presser, Aarhus University: 

> Attached is the right version.
> Please point at https://international.au.dk

I uploaded his attachment on the Drive, entitled NEW aarhus university logo. Hope the format he sent is ok.

**Comment by maribati** [comment]
(04/06), response from Iryna Shuvaieva, DeLab (University of Warsaw):

> I confirm you can use the logo. If linked, it should point to:http://en.uw.edu.pl/
> Feel free to use logos from this source:
> in case UW logo is higher than 20 mm:  http://promocja.uw.edu.pl/logo-w-wersji-angielskiej-powyzej-20-mm/
> in case UW logo is lower than 20 mm:    http://promocja.uw.edu.pl/logo-w-wersji-angielskiej-ponizej-20-mm/

**Comment by tanius** [comment]
At this stage, everything about this issue is done except:

* answer by City of Amsterdam, and adding the logo according to that
* answer by Nesta Italia, and adding the logo according to that

**Comment by maribati** [comment]
Sent the reminders to both. 

(14/6), response from Simona Bielli (NESTA Italia)

> You can of course use it. At the moment we don't have an NGI forward page of the project, you could point the logo to our website: https://www.nestaitalia.org/

The logo is uploaded on the Drive.

**Comment by maribati** [comment]
(17/6), response from Tamas Erkelens (the City of Amsterdam):

> Herewith official english logo and permission to use it
https://assets.amsterdam.nl/publish/pages/858225/gasd_e_2017_v4_rgb_236.zip

you can point to
https://www.amsterdam.nl/

**Comment by tanius** [comment]
The remaining logos and links (Nesta Itali and City of Amsterdam) are online now, see https://ngi.edgeryders.eu/#partners

That completes the work on this issue.
