### ISSUE TITLE
Fill the "About" dropdown menu according to the H3 headings in the text

### ISSUE THREAD

**Issue by tanius** [edgeryders/ngi-forward-platform#17]
The dropdown menu is in general already made from the relevant H3 headings. But one menu item is missing and others are in a different order.

The correct, full list of menu items with their links is:

* Overview, `#overview`
* Consortium, `#consortium`
* Privacy & Consent, `#privacy`
* Legal information, `#legals`
* Project Deliverables, `#deliverables`
* Resources, `#resources`

(Also, I just added the relevant `id` attributes to the content over at Discourse so that the links do now work.)

**Comment by damingo** [comment]
Done.
