### ISSUE TITLE
Make "Share your Experience" a page inside this website

### ISSUE THREAD

**Issue by tanius** [edgeryders/ngi-forward-platform#31]
To not confuse people too early with switching over to the Edgeryders website for posting, the menu item "Share your Experience" should point to a new page inside this website.

That page would have the following content:

* An intro paragraph imported from Discourse posts, with the usual technique we use.
* Another "Share your Experience" button, as used on the frontpage.
* A table with the recent posts in the ["Tell your Story" category](https://edgeryders.eu/c/ioh/tell-your-story). So basically the same "Activity" table as used on the frontpage, but the data source limited to just this one "Tell your Story" Discourse category.
* A bit of statistics about the "Tell your Story" category, maybe displayed over the "recent posts" table as a few cards with one bit number and a small description each. The statistics could include: 
    * number of users who posted in the category ("121 people sharing")
    * number of posts in the category ("200 stories")
    * number of comments in the category, which here means "number of posts minus number of topics" ("567 comments")
    * … something else maybe? If there's any other good metric, just add it.

**Comment by albertocottica** [comment]
No need to include many stats. I think I read somewhere that dashboard-y pages do not invite engagement.
