### ISSUE TITLE
Make "Events" a page inside this website

### ISSUE THREAD

**Issue by tanius** [edgeryders/ngi-forward-platform#32]
Like the new "Share your experience" page (see #31), the menu item "Events" should point to a new page inside this website.

That page would have the following content: one card for each upcoming event.

Upcoming events are topics in category [Internet of Humans](https://edgeryders.eu/c/ioh) that are tagged with tag [upcoming-event](https://edgeryders.eu/tags/upcoming-event) (which is not used yet, but will be). This excludes topics about events after they happened and also topics with reflections about events, speculative planning for events etc.. We could further limit to category [Internet of Humans → Events](https://edgeryders.eu/c/ioh/events), but better don't because sometimes people will place event invitations into other sub-categories by mistake.

Each card should contain:

* **Teaser image.** Take the first image from the first post of the topic; if there is no image in the first post, take a default placeholder image.

* **Event title.** Take the title of the topic. By convention, this would also always contain the date of the event.

* **Event description.** Take the first paragraph of the first post of the topic. Usually, this paragraph will contain all the essentials about the event (location, date, how to attend, short description). If the paragraph is very short, better include another one, until a certain minimum length is met.

* **"Read More" link.** This will point to the topic on edgeryders.eu, with the usual on-hover note "Link goes to our content creation platform".

**Comment by damingo** [comment]
Done.
