### ISSUE TITLE
Background image not loading? 

### ISSUE THREAD

**Issue by albertocottica** [edgeryders/ngi-forward-platform#39]
![image](https://user-images.githubusercontent.com/1976806/59775723-ecba2680-92b1-11e9-9de0-27295c9c5958.png)

**Comment by tanius** [comment]
Hmm but the binary digits background image is there in your screenshot. Is the network animation moving? Then everything would be as expected.

What did you expect instead?

**Comment by albertocottica** [comment]
The network animation moves.

 I was expecting something like https://www.ngi.eu/. Is the background image a placeholder?

**Comment by tanius** [comment]
Every visual element on that platform is a placeholder right now, waiting for the design specs.

If the design specs don't want an element changed, it would stay in place, including the binary digits background image.

**Comment by albertocottica** [comment]
Noted. Please ask Marina to remind the NESTA folks, I would not want the platform to look like that at our 2nd of July meeting.
