### ISSUE TITLE
Adapt the menu font

### ISSUE THREAD

**Issue by tanius** [edgeryders/ngi-forward-platform#5]
The menu font uses the text size of normal text paragraphs in the page right now. That's a bit small, and also it's "gray on gray".

Instead, let's switch to using the same menu font [as used on ngi.eu](https://www.ngi.eu/), which is also the best bet to match the more detailed design requirements we'll get:

* all caps
* `color: white`
* `font-weight: 700`
* `font-size: 14px` (ngi.eu has `12px` but that's a bit on the small side)

**Comment by damingo** [comment]
Done.
