### ISSUE TITLE
Add a separator before the footer element

### ISSUE THREAD

**Issue by tanius** [edgeryders/ngi-forward-platform#6]
Currently, it is not visually obvious where the site's main content ends and the "This project has received funding from …" footer begins.

Please use a light gray, full-width background as seen on [consultation.ngi.eu](https://consultation.ngi.eu/). And since the content area of the site is not full-width, let's separate it from that content area with a bit of gap through which the "10101000100111100110" background can be seen.

So in principle it will look like the top navbar mirrored on the bottom.

This seems to be a suitable choice that fits into the official design guide, while avoiding large areas of "that green NGI color" which can be "a bit too much". So, we'd not want to do it _exactly_ the same way as the footer on [ngi.eu](https://www.ngi.eu/) itself.

**Comment by damingo** [comment]
Done.
