### ISSUE TITLE
Separate the main content sections more prominently

### ISSUE THREAD

**Issue by tanius** [edgeryders/ngi-forward-platform#7]
Currently, the main sections start with H2 headers and are contained in a `<section id="…" …>` element each. Since they are the main sections, they should be separated from the other main sections with the most obvious visual separation technique that will be used on the website.

Alternatives include (among other suitable options):

* A gap in the white background, through which one would see the "101100100101000101011110010" background.

* Different text background colors, as seen on [openvillage.edgeryders.eu](http://openvillage.edgeryders.eu/). However, as we also use the "101100100101000101011110010", this might create a visual mess.

**Comment by damingo** [comment]
Done.
