### ISSUE TITLE
Add the particle animation in the topmost content section

### ISSUE THREAD

**Issue by tanius** [edgeryders/ngi-forward-platform#9]
Would be great to have a particle network animation (as [seen here](http://openvillage.edgeryders.eu/)) in the topmost content section "A community working together to build a human centric next generation Internet".

There are multiple repos providing code for this kind of thing. At first glance, the most suitable seems to be [this repo](https://github.com/VincentGarreau/particles.js) because (1) it seems to be the most well-known and most maintained and (2) it [can be installed as a gem](https://github.com/VincentGarreau/particles.js/#rails-assets).

Let's only provide a few, relatively slow-moving particles (means, so that a low framerate is fine). Otherwise the site would hog people's CPU, which is really annoying …

And if adding this gimmick turns out to be somehow difficult, let's leave it for later.

**Comment by damingo** [comment]
Done.
